name: Deploying .NET to IIS

on: 
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build-dotnet-app:
    name: Build Dotnet App
    runs-on: ubuntu-18.04
    steps: 

      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.405'

      - name: verify donet installation 
        run: dotnet --version

      - Name: publish dotnet 
        run: dotnet pulish -o output

    